language: node_js
node_js:
- '8'
install:
- npm install
script:
- npm test
deploy:
  on:
    tags: true
  provider: npm
  email: julien.baillagou@gmail.com
  api_key:
    secure: REKnf8yCMlKTxiltfwp/d5dOh4Ga8JIbZu50em9Hkt32eRv95D/vYjnKLO/0s1zP+UXHjEuHnwOxJLamSYmt2XJXElEUTFvyCjFBP7Z5rGOY9ZQSaT2R+MKnAb/D08IN0lPH9vNNBur3crAPfhDthlu1kwzY0mukUa7o9VplhEkWGSQnKC4H4PzFllbA2D916qZwIr1LGRlNliIM9EhDDYIud8LMAvjP0Fpcm2MXMhRfsRY4S6egzRsDQQRZ1BzlADNIJqSiMiGcgCCYC4i9eiq4dV+rlEHWsJxzZ8omlCxQFhCCgF60WWzRbLdbuaH6wZm3fuuAUv9hMujVfkgMOe8zUeKUKNdqr3cg1K3odZ/1qmmH9tp86pxTiuczmmP/tSH59sFxiy9mhMtaPTCXvibrAXLMLH5OqXIXtfubLkomScaJJizEFDfK/VUjG13aGaWHDHJHc3qfEBjmsYzDuiDC0bpJgJie9l8W571CgETgMMt/Xrhqu8HezlDs/wcyTocJ3J4Usx5Tl4GQCL7bHxSLjnGXsWS+SE6TdLnZO6OLVEv8ZVRRTvuLlxFrjIxV7FRBLfBd6UXXU3vK5pWJnsu5WAhl1l47bwTqNTg2LGM1s1Sf7lxdA3xmysIMZcBUpbju9ANJIm83nrZ9A++Vg3mER+R3ujFqOZQf23imzL0=
