language: node_js
node_js:
- '8'
install:
- npm install
script:
- npm test
deploy:
  on:
    tags: true
    branch: master
  provider: npm
  email: julien.baillagou@gmail.com
  api_key:
    secure: VQqqzjVZlSBdkN+wgxyS357JuIq6nGGf5l4bsj4RqKm1vHPwXbO9F9sbUE8VJku6y5zfiwGOkBGPZERT23qiQ5/cG/siZcrbNNwcY5qUiFL4QQqnrCxU/i0tNj/4B4j6ntpP/qnLT19I1nfdUtv2T+5IPS83C0rTy/YYZeTiUaSPYauSU7ZRLBKiIbUcfE0iUbsSM1pwJegrHGLgNVBR2eyeAqgTRazUeKBYCVrXPRumAiCQ+XJ3RZUZG2VM9SoU9jcx6QlfvYVyeivXvq7tBCox8iGF9xxqKbmG83CV/XumWbeFQKgc6SLXLjK2tsI/ZYEmtCGfrsPlmBt70BJSsczmvxaonYOCepqrPsJMKlS+O0AOrubxeVJY3sED1rlL4ee0HtYrlUZxasWRGK3497lFSuY9p0ENC2JIBeF5msqf1P6Mb2Pn1c3n8bVSdBvH+CdCSynnJg4lRowP7DV+XFte5ajIgVJyLP+YUL62qhhuSLACfVK8SzZLutN8FYEm+xWjVoDxF33yi8vMnQnyW9glXv3VDC98AXFH3kXYqPJ6/gCfV5sb5kcmZkWZSQPC5jn057VRGXY6ZR5DweXDuy3tn7UHtdeyA7l3LP9W8wD3JX2gCXihVNzHWGPW7C6KUzFk4IQx3ElELRNnrsGBQOjF8Sw9IPJXAn6LzCFilIY=
